version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      
..:/workspace:cached
  ports:
8000:8000
depends_on:
db
environment:
  DB_CONNECTION: pgsql
  DB_HOST: db
  DB_PORT: 5432
  DB_DATABASE: sociotorcedor
  DB_USERNAME: postgres
  DB_PASSWORD: 170202

  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 170202
      POSTGRES_DB: laravel
    ports:
      
"5432:5432"
  volumes:
pgdata:/var/lib/postgresql/data

volumes:
  pgdata: